  CREATE TABLE "EMPREGADO" 
   (	"NOME" VARCHAR2(50), 
	"RG" VARCHAR2(8), 
	"CIC" VARCHAR2(8), 
	"DEPTO" NUMBER(*,0), 
	"RG_SUPERVISOR" VARCHAR2(8), 
	"SALARIO" NUMBER(10,2), 
	 PRIMARY KEY ("RG")
  USING INDEX  ENABLE
   ) ;

/////////////////////////////////////////////////////////////

  CREATE TABLE "DEPARTAMENTO" 
   (	"NOME" VARCHAR2(50), 
	"NUMERO" NUMBER(*,0), 
	"RG_GERENTE" VARCHAR2(8), 
	 PRIMARY KEY ("NUMERO")
  USING INDEX  ENABLE
   ) ;

/////////////////////////////////////////////////////////////

  CREATE TABLE "PROJETO" 
   (	"NOME" VARCHAR2(50), 
	"NUMERO" NUMBER(*,0), 
	"LOCALIZACAO" VARCHAR2(50), 
	 PRIMARY KEY ("NUMERO")
  USING INDEX  ENABLE
   ) ;

/////////////////////////////////////////////////////////////

  CREATE TABLE "DEPENDENTES" 
   (	"RG_RESPONSAVEL" VARCHAR2(8), 
	"NOME_DEPENDENTE" VARCHAR2(50), 
	"NASCIMENTO" DATE, 
	"RELACAO" VARCHAR2(50), 
	"SEXO" VARCHAR2(10), 
	 PRIMARY KEY ("RG_RESPONSAVEL", "NOME_DEPENDENTE")
  USING INDEX  ENABLE
   ) ;

/////////////////////////////////////////////////////////////

  CREATE TABLE "DEPARTAMENTO_PROJETO" 
   (	"NUMERO_DEPTO" NUMBER(*,0), 
	"NUMERO_PROJETO" NUMBER(*,0), 
	 PRIMARY KEY ("NUMERO_DEPTO", "NUMERO_PROJETO")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "DEPARTAMENTO_PROJETO" ADD FOREIGN KEY ("NUMERO_DEPTO")
	  REFERENCES "DEPARTAMENTO" ("NUMERO") ENABLE;
  ALTER TABLE "DEPARTAMENTO_PROJETO" ADD FOREIGN KEY ("NUMERO_PROJETO")
	  REFERENCES "PROJETO" ("NUMERO") ENABLE;

/////////////////////////////////////////////////////////////

  CREATE TABLE "EMPREGADO_PROJETO" 
   (	"RG_EMPREGADO" VARCHAR2(8), 
	"NUMERO_PROJETO" NUMBER(*,0), 
	"HORAS" NUMBER(*,0), 
	 PRIMARY KEY ("RG_EMPREGADO", "NUMERO_PROJETO")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "EMPREGADO_PROJETO" ADD FOREIGN KEY ("RG_EMPREGADO")
	  REFERENCES "EMPREGADO" ("RG") ENABLE;
  ALTER TABLE "EMPREGADO_PROJETO" ADD FOREIGN KEY ("NUMERO_PROJETO")
	  REFERENCES "PROJETO" ("NUMERO") ENABLE;
